name: Bug Report
description: File a bug report
labels: [bug]
issue_body: true
body:
- type: dropdown
  id: extension
  attributes:
    label: Azure DevOps Extensions
    description: "There are a number of Azure DevOps extensions in this repo so please state which one the bug relates to"
    options:
      - Artifact PR Description
      - Built Utilities
      - DevTest Labs 
      - File Copier
      - Generate Release Notes (Node Cross Platform)
      - Generate Release Notes (Legacy PowerShell)
      - Manifest Versioning
      - WIKI Updater
      - WIKI PDF Generator
      - YAML Generator 
      - Other
  validations:
    required: true
