name: Question
description: Ask a question about usage of an extension in this project
labels: [question]
title: Please don't create an quesiton issue, open a discussion
issue_body: true
body:
- type: markdown
  attributes:
    value: |
      ## Please don't create an issue when you have a question
      Rather than creating an Issue please use the new [discussions](https://github.com/rfennell/AzurePipelines/discussions/new) feature of GitHub
